gaia = db.getSiblingDB('gaia');
gaia.stack.drop();
gaia.stack.insert([
  {
    '_id': '5a215b6b-fe53-4afa-85f0-a10175a7f264',
    'module': { '$ref': 'terraformModule', '$id': 'e01f9925-a559-45a2-8a55-f93dc434c676' },
    'name': 'mongo-instance-1',
    'description': 'first instance of mongo module',
    'variableValues': {
      'mongo_container_name': 'test',
      'mongo_exposed_port': '27117',
    },
    'providerSpec': 'provider "docker" {\n    host = "unix:///var/run/docker.sock"\n}',
    'state': 'NEW',
    'ownerOrganization': { '$ref': 'organization', '$id': 'Ze Organization' },
    'estimatedRunningCost': null,
    'createdBy': { '$ref': 'user', '$id': 'admin' },
    'createdAt': new Date(),
    'updatedBy': null,
    'updatedAt': null,
  },
  {
    '_id': '143773fa-4c2e-4baf-a7fb-79d23e01c5ca',
    'module': { '$ref': 'terraformModule', '$id': 'e01f9925-a559-45a2-8a55-f93dc434c676' },
    'name': 'mongo-instance-2',
    'description': 'second instance of mongo module',
    'variablesValues': {},
    'providerSpec': null,
    'state': 'NEW',
    'ownerOrganization': { '$ref': 'organization', '$id': 'Ze Organization' },
    'estimatedRunningCost': null,
    'createdBy': { '$ref': 'user', '$id': 'admin' },
    'createdAt': new Date(),
    'updatedBy': null,
    'updatedAt': null,
  },
  {
    '_id': '845543d0-20a5-466c-8978-33c9a4661606',
    'module': { '$ref': 'terraformModule', '$id': 'e01f9925-a559-45a2-8a55-f93dc434c676' },
    'name': 'mongo-instance-limited',
    'description': 'instance of mongo module for organization Not Ze Organization',
    'variablesValues': {},
    'providerSpec': null,
    'state': 'NEW',
    'ownerOrganization': { '$ref': 'organization', '$id': 'Not Ze Organization' },
    'estimatedRunningCost': null,
    'createdBy': { '$ref': 'user', '$id': 'Mary J' },
    'createdAt': new Date(),
    'updatedBy': null,
    'updatedAt': null,
  },
  {
    '_id': 'de28a01f-257a-448d-8e1b-00e4e3a41db2',
    'module': { '$ref': 'terraformModule', '$id': 'e01f9925-a559-45a2-8a55-f93dc434c676' },
    'variableValues': {
      'mongo_container_name': 'local-mongo',
      'mongo_exposed_port': '28017',
    },
    'name': 'local-mongo',
    'description': 'local docker mongo container',
    'state': 'RUNNING',
    'estimatedRunningCost': '0',
    'createdBy': {
      '$ref': 'user',
      '$id': 'admin',
    },
    'createdAt': ISODate('2020-02-03T17:57:07.341Z'),
    'updatedBy': {
      '$ref': 'user',
      '$id': 'admin',
    },
    'updatedAt': ISODate('2020-02-05T07:01:29.935Z'),
    '_class': 'io.gaia_app.stacks.bo.Stack',
  },
  {
    '_id': 'archived-stack',
    'name': 'archived-stack',
    'description': 'archived stack for testing purpose',
    'state': 'ARCHIVED',
    '_class': 'io.gaia_app.stacks.bo.Stack',
  },
]);
